Repository CreandoCuba/Universidad-de-Ciencias-Medicas-de-Matanzas-ID0018, pull requests merged in 2024-05, with the labels that each got.

#53 Reseña al museo de la Universidad creada
  Plantilla 2/about.html
Labels: duplicate

#52 Apartado de Mantengase informado ha sido agregado al footer
  Plantilla 2/index.html
Labels: good first issue

#56 updated mantengase informado
  Plantilla 2/about.html
  Plantilla 2/docencia.html
  Plantilla 2/doctorado.html
  Plantilla 2/facultades.html
  Plantilla 2/maestria.html
  Plantilla 2/postgrado.html
  Plantilla 2/pregrado.html
Labels: enhancement
